package com.viplav.financegeorgia.db;
// Generated Nov 30, 2013 12:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private Integer projectId;
     private String documentKey;
     private String document;
     private String downloadedDocument;
     private Date createdate;
     private Date updatedate;
     private Byte deletedind;
     private String documentscol;

    public Documents() {
    }

    public Documents(Integer userId, Integer projectId, String documentKey, String document, String downloadedDocument, Date createdate, Date updatedate, Byte deletedind, String documentscol) {
       this.userId = userId;
       this.projectId = projectId;
       this.documentKey = documentKey;
       this.document = document;
       this.downloadedDocument = downloadedDocument;
       this.createdate = createdate;
       this.updatedate = updatedate;
       this.deletedind = deletedind;
       this.documentscol = documentscol;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
    public String getDocumentKey() {
        return this.documentKey;
    }
    
    public void setDocumentKey(String documentKey) {
        this.documentKey = documentKey;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public String getDownloadedDocument() {
        return this.downloadedDocument;
    }
    
    public void setDownloadedDocument(String downloadedDocument) {
        this.downloadedDocument = downloadedDocument;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }
    
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    public Byte getDeletedind() {
        return this.deletedind;
    }
    
    public void setDeletedind(Byte deletedind) {
        this.deletedind = deletedind;
    }
    public String getDocumentscol() {
        return this.documentscol;
    }
    
    public void setDocumentscol(String documentscol) {
        this.documentscol = documentscol;
    }




}


