package com.viplav.financegeorgia.db;
// Generated Nov 30, 2013 12:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Investment generated by hbm2java
 */
public class Investment  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private Integer projectId;
     private Integer amount;
     private Integer commission;
     private Date createdate;
     private Date updatedate;
     private Byte deletedind;

    public Investment() {
    }

    public Investment(Integer userId, Integer projectId, Integer amount, Integer commission, Date createdate, Date updatedate, Byte deletedind) {
       this.userId = userId;
       this.projectId = projectId;
       this.amount = amount;
       this.commission = commission;
       this.createdate = createdate;
       this.updatedate = updatedate;
       this.deletedind = deletedind;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Integer getCommission() {
        return this.commission;
    }
    
    public void setCommission(Integer commission) {
        this.commission = commission;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }
    
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    public Byte getDeletedind() {
        return this.deletedind;
    }
    
    public void setDeletedind(Byte deletedind) {
        this.deletedind = deletedind;
    }




}


