package com.viplav.financegeorgia.db;
// Generated Nov 30, 2013 12:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private LocationId id;
     private String address;
     private String city;
     private String state;
     private String zip;
     private String country;
     private String website;
     private String facebook;
     private String googlePlus;
     private String twitter;
     private String linkedin;
     private String phone1;
     private String mobile;
     private String fax;
     private Date createdate;
     private Date updatedate;
     private Boolean deletedind;

    public Location() {
    }

	
    public Location(LocationId id) {
        this.id = id;
    }
    public Location(LocationId id, String address, String city, String state, String zip, String country, String website, String facebook, String googlePlus, String twitter, String linkedin, String phone1, String mobile, String fax, Date createdate, Date updatedate, Boolean deletedind) {
       this.id = id;
       this.address = address;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.country = country;
       this.website = website;
       this.facebook = facebook;
       this.googlePlus = googlePlus;
       this.twitter = twitter;
       this.linkedin = linkedin;
       this.phone1 = phone1;
       this.mobile = mobile;
       this.fax = fax;
       this.createdate = createdate;
       this.updatedate = updatedate;
       this.deletedind = deletedind;
    }
   
    public LocationId getId() {
        return this.id;
    }
    
    public void setId(LocationId id) {
        this.id = id;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getGooglePlus() {
        return this.googlePlus;
    }
    
    public void setGooglePlus(String googlePlus) {
        this.googlePlus = googlePlus;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getLinkedin() {
        return this.linkedin;
    }
    
    public void setLinkedin(String linkedin) {
        this.linkedin = linkedin;
    }
    public String getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }
    
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    public Boolean getDeletedind() {
        return this.deletedind;
    }
    
    public void setDeletedind(Boolean deletedind) {
        this.deletedind = deletedind;
    }




}


