package com.viplav.financegeorgia.db;
// Generated Nov 30, 2013 12:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private Integer roleId;
     private String firstName;
     private String mi;
     private String lastName;
     private String email;
     private String password1;
     private String image;
     private String investorType;
     private Boolean pptosnda;
     private Date createdate;
     private Date updatedate;
     private Boolean deletedind;
     private Byte locked;
     private String passresetKey;
     private Date dob;
     private String aboutMe;

    public User() {
    }

	
    public User(String username) {
        this.username = username;
    }
    public User(String username, Integer roleId, String firstName, String mi, String lastName, String email, String password1, String image, String investorType, Boolean pptosnda, Date createdate, Date updatedate, Boolean deletedind, Byte locked, String passresetKey, Date dob, String aboutMe) {
       this.username = username;
       this.roleId = roleId;
       this.firstName = firstName;
       this.mi = mi;
       this.lastName = lastName;
       this.email = email;
       this.password1 = password1;
       this.image = image;
       this.investorType = investorType;
       this.pptosnda = pptosnda;
       this.createdate = createdate;
       this.updatedate = updatedate;
       this.deletedind = deletedind;
       this.locked = locked;
       this.passresetKey = passresetKey;
       this.dob = dob;
       this.aboutMe = aboutMe;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMi() {
        return this.mi;
    }
    
    public void setMi(String mi) {
        this.mi = mi;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword1() {
        return this.password1;
    }
    
    public void setPassword1(String password1) {
        this.password1 = password1;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getInvestorType() {
        return this.investorType;
    }
    
    public void setInvestorType(String investorType) {
        this.investorType = investorType;
    }
    public Boolean getPptosnda() {
        return this.pptosnda;
    }
    
    public void setPptosnda(Boolean pptosnda) {
        this.pptosnda = pptosnda;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }
    
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
    public Boolean getDeletedind() {
        return this.deletedind;
    }
    
    public void setDeletedind(Boolean deletedind) {
        this.deletedind = deletedind;
    }
    public Byte getLocked() {
        return this.locked;
    }
    
    public void setLocked(Byte locked) {
        this.locked = locked;
    }
    public String getPassresetKey() {
        return this.passresetKey;
    }
    
    public void setPassresetKey(String passresetKey) {
        this.passresetKey = passresetKey;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getAboutMe() {
        return this.aboutMe;
    }
    
    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }




}


